[project]
name = "dqxp"
dynamic = ["version"]
description = "DQX extension library providing additional data quality analysis tables"
license-files = { paths = ["LICENSE.md"] }
requires-python = ">=3.11"
authors = [
    {name = "Greg Hansen", email = "gregory.hansen@databricks.com"},
]
maintainers = [
    {name = "Greg Hansen", email = "gregory.hansen@databricks.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "databricks-labs-dqx>=0.13.0",
    "pyspark>=3.5.0",
]

[build-system]
requires = ["hatchling>=1.9.0"]
build-backend = "hatchling.build"

[tool.hatch.build]
sources = ["src"]
include = ["src"]

[tool.hatch.envs.default]
type = "virtual"
path = ".venv"

dependencies = [
    "pytest>=8.0",
    "pytest-cov>=4.1",
    "ruff>=0.3",
    "black>=24.0",
    "pandas",
]

[tool.hatch.version]
path = "src/dqxp/__about__.py"

[tool.pytest.ini_options]
addopts = "--no-header -v"
pythonpath = ["src"]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.black]
target-version = ["py311"]
line-length = 120
